### ISSUE TITLE
Can't create directories more than one deep

### ISSUE THREAD

**Issue by matdombrock** [matdombrock/SteelSky#3]
For example, the app can create the directory `/wiki/` but can not create the directory `/wiki/audio/`. 

```
fs.js:885
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir '/var/www/SSSource/../html/wiki/audio'
    at Object.fs.mkdirSync (fs.js:885:18)
    at convert (/var/www/SteelSky/steelsky.js:72:8)
    at Object.<anonymous> (/var/www/SteelSky/steelsky.js:101:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
```

Manually creating the `wiki` directory in the output directory is a workaround.

**Comment by matdombrock** [comment]
This is solved by making the `mkdir` command recursive.
